apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
  labels: 
    app: replica-set-app
spec: 
  selector:
    matchExpressions:
        - { key: app, operator: In , values: [replica-set-app]} 
  
  replicas: 4
  template:
    metadata:
      labels:
        name: nginxapp
        app: replica-set-app
    spec:
      containers:
        - name: nginxapp
          image: nginx
          ports:
              - containerPort: 80
                protocol: TCP