apiVersion: v1
kind: ReplicationControler
metadata:
  name: replica-controler
  labels: 
    app: replica-controler-app
spec: 
  selector: 
    app: replica-controler-app
    replicas: 4
    template:
      metadata:
        labels:
          name: nginxapp
          app: replica-controler-app
      spec:
        containers:
          - name: nginxapp
            image: nginx
            ports:
              - containerPort: 80
                protocol: TCP